#!/usr/bin/env python3
"""Audit PTB-XL annotation metadata before defining label reliability L.

This script is descriptive only.

It does NOT:
- change labels,
- change the cohort,
- interpret validated_by as confidence,
- treat likelihood=0 as zero confidence,
- define a reliability score.
"""

from __future__ import annotations

import ast
import json
from datetime import datetime, timezone

import numpy as np
import pandas as pd

from ptbxl_reliability.integrity import sha256_file
from ptbxl_reliability.labels import SUPERCLASS_ORDER
from ptbxl_reliability.paths import PROJECT_ROOT


RAW_ROOT = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "ptb-xl"
    / "1.0.3"
)

DATABASE_PATH = (
    RAW_ROOT
    / "ptbxl_database.csv"
)

SCP_PATH = (
    RAW_ROOT
    / "scp_statements.csv"
)

MANIFEST_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "cohort"
    / "v1"
    / "ptbxl_superdiagnostic_cohort.csv"
)

OUTPUT_PATH = (
    PROJECT_ROOT
    / "logs"
    / "label_reliability_metadata_audit.json"
)


def parse_scp_codes(value) -> dict[str, float]:
    if not isinstance(value, str):
        raise ValueError(
            f"scp_codes must be string, found {type(value)}"
        )

    parsed = ast.literal_eval(value)

    if not isinstance(parsed, dict):
        raise ValueError(
            "scp_codes did not parse to a dictionary"
        )

    result = {}

    for code, likelihood in parsed.items():
        value_float = float(likelihood)

        if not np.isfinite(value_float):
            raise ValueError(
                f"Non-finite likelihood for {code}"
            )

        if (
            value_float < 0.0
            or value_float > 100.0
        ):
            raise ValueError(
                f"Likelihood outside [0,100] for {code}"
            )

        result[str(code)] = value_float

    return result


def normalize_bool(value):
    if pd.isna(value):
        return None

    if isinstance(value, (bool, np.bool_)):
        return bool(value)

    text = str(value).strip().lower()

    if text in {"true", "1", "1.0"}:
        return True

    if text in {"false", "0", "0.0"}:
        return False

    raise ValueError(
        f"Unexpected boolean representation: {value!r}"
    )


def summarize_boolean(series: pd.Series) -> dict:
    values = [
        normalize_bool(value)
        for value in series.tolist()
    ]

    return {
        "true": int(
            sum(value is True for value in values)
        ),
        "false": int(
            sum(value is False for value in values)
        ),
        "missing": int(
            sum(value is None for value in values)
        ),
    }


def likelihood_summary(values: list[float]) -> dict:
    if not values:
        return {
            "count": 0,
            "min": None,
            "q25": None,
            "median": None,
            "mean": None,
            "q75": None,
            "max": None,
        }

    array = np.asarray(
        values,
        dtype=np.float64,
    )

    return {
        "count": int(array.size),
        "min": float(np.min(array)),
        "q25": float(np.quantile(array, 0.25)),
        "median": float(np.median(array)),
        "mean": float(
            np.mean(
                array,
                dtype=np.float64,
            )
        ),
        "q75": float(np.quantile(array, 0.75)),
        "max": float(np.max(array)),
    }


def main() -> None:
    database = pd.read_csv(
        DATABASE_PATH
    )

    scp = pd.read_csv(
        SCP_PATH,
        index_col=0,
    )

    manifest = pd.read_csv(
        MANIFEST_PATH
    )

    if len(manifest) != 21388:
        raise ValueError(
            f"Expected 21388 frozen records, found {len(manifest)}"
        )

    required_database_columns = {
        "ecg_id",
        "scp_codes",
        "validated_by",
        "second_opinion",
        "initial_autogenerated_report",
        "validated_by_human",
        "strat_fold",
    }

    missing = (
        required_database_columns
        - set(database.columns)
    )

    if missing:
        raise ValueError(
            f"Missing PTB-XL metadata fields: {sorted(missing)}"
        )

    if "diagnostic" not in scp.columns:
        raise ValueError(
            "scp_statements.csv lacks diagnostic column"
        )

    if "diagnostic_class" not in scp.columns:
        raise ValueError(
            "scp_statements.csv lacks diagnostic_class column"
        )

    diagnostic_mask = (
        pd.to_numeric(
            scp["diagnostic"],
            errors="coerce",
        )
        .fillna(0)
        .astype(int)
        .eq(1)
    )

    diagnostic_scp = scp.loc[
        diagnostic_mask
    ].copy()

    code_to_class = {}

    for code, row in diagnostic_scp.iterrows():
        superclass = row["diagnostic_class"]

        if pd.isna(superclass):
            continue

        superclass = str(
            superclass
        ).strip()

        if superclass not in SUPERCLASS_ORDER:
            raise ValueError(
                f"Unexpected diagnostic superclass "
                f"{superclass!r} for code {code!r}"
            )

        code_to_class[
            str(code)
        ] = superclass

    merged = manifest.merge(
        database[
            [
                "ecg_id",
                "scp_codes",
                "validated_by",
                "second_opinion",
                "initial_autogenerated_report",
                "validated_by_human",
                "strat_fold",
            ]
        ],
        on="ecg_id",
        how="left",
        validate="one_to_one",
        suffixes=(
            "_manifest",
            "_database",
        ),
    )

    if len(merged) != len(manifest):
        raise ValueError(
            "Metadata merge changed cohort size"
        )

    if merged["scp_codes"].isna().any():
        raise ValueError(
            "Some frozen ECGs lack source scp_codes"
        )

    if not np.array_equal(
        merged["strat_fold_manifest"].to_numpy(),
        merged["strat_fold_database"].to_numpy(),
    ):
        raise ValueError(
            "Manifest/source fold mismatch"
        )

    provenance_by_split = {}

    for split in (
        "train",
        "validation",
        "test",
    ):
        subset = merged.loc[
            merged["split"].eq(split)
        ]

        provenance_by_split[
            split
        ] = {
            "records": int(len(subset)),

            "validated_by_human":
                summarize_boolean(
                    subset[
                        "validated_by_human"
                    ]
                ),

            "second_opinion":
                summarize_boolean(
                    subset[
                        "second_opinion"
                    ]
                ),

            "initial_autogenerated_report":
                summarize_boolean(
                    subset[
                        "initial_autogenerated_report"
                    ]
                ),

            "validated_by_nonmissing":
                int(
                    subset[
                        "validated_by"
                    ]
                    .notna()
                    .sum()
                ),

            "validated_by_missing":
                int(
                    subset[
                        "validated_by"
                    ]
                    .isna()
                    .sum()
                ),

            "unique_nonmissing_validated_by_ids":
                int(
                    subset[
                        "validated_by"
                    ]
                    .dropna()
                    .nunique()
                ),
        }

    # PTB-XL's recommended fold construction should make
    # validation/test certainly human-validated.
    for split in (
        "validation",
        "test",
    ):
        summary = provenance_by_split[
            split
        ][
            "validated_by_human"
        ]

        if (
            summary["false"] != 0
            or summary["missing"] != 0
        ):
            raise ValueError(
                f"{split}: expected validated_by_human "
                "to be true for every record"
            )

    class_stats = {
        split: {
            label: {
                "positive_records": 0,
                "records_with_any_known_likelihood": 0,
                "records_with_all_likelihoods_unknown": 0,
                "records_with_multiple_contributing_codes": 0,
                "contributing_code_entries": 0,
                "known_likelihood_entries": 0,
                "unknown_likelihood_entries": 0,
                "_known_values": [],
            }
            for label in SUPERCLASS_ORDER
        }
        for split in (
            "train",
            "validation",
            "test",
        )
    }

    record_level = {
        split: {
            "records": 0,
            "records_with_any_known_diagnostic_likelihood": 0,
            "records_with_no_known_diagnostic_likelihood": 0,
        }
        for split in (
            "train",
            "validation",
            "test",
        )
    }

    for row in merged.itertuples(
        index=False
    ):
        split = str(row.split)

        codes = parse_scp_codes(
            row.scp_codes
        )

        class_values = {
            label: []
            for label in SUPERCLASS_ORDER
        }

        all_diagnostic_likelihoods = []

        for code, likelihood in codes.items():
            superclass = code_to_class.get(
                code
            )

            if superclass is None:
                continue

            class_values[
                superclass
            ].append(
                float(likelihood)
            )

            all_diagnostic_likelihoods.append(
                float(likelihood)
            )

        record_level[
            split
        ]["records"] += 1

        if any(
            value > 0.0
            for value
            in all_diagnostic_likelihoods
        ):
            record_level[
                split
            ][
                "records_with_any_known_diagnostic_likelihood"
            ] += 1
        else:
            record_level[
                split
            ][
                "records_with_no_known_diagnostic_likelihood"
            ] += 1

        for label in SUPERCLASS_ORDER:
            expected_positive = int(
                getattr(
                    row,
                    label
                )
            )

            values = class_values[
                label
            ]

            observed_positive = int(
                len(values) > 0
            )

            if observed_positive != expected_positive:
                raise ValueError(
                    f"ECG {row.ecg_id}: source SCP mapping "
                    f"does not reproduce frozen {label} target"
                )

            if not observed_positive:
                continue

            stats = class_stats[
                split
            ][
                label
            ]

            stats[
                "positive_records"
            ] += 1

            stats[
                "contributing_code_entries"
            ] += len(values)

            if len(values) > 1:
                stats[
                    "records_with_multiple_contributing_codes"
                ] += 1

            known = [
                value
                for value in values
                if value > 0.0
            ]

            unknown_count = (
                len(values)
                - len(known)
            )

            stats[
                "known_likelihood_entries"
            ] += len(known)

            stats[
                "unknown_likelihood_entries"
            ] += unknown_count

            stats[
                "_known_values"
            ].extend(
                known
            )

            if known:
                stats[
                    "records_with_any_known_likelihood"
                ] += 1
            else:
                stats[
                    "records_with_all_likelihoods_unknown"
                ] += 1

    finalized_class_stats = {}

    for split, split_values in class_stats.items():
        finalized_class_stats[
            split
        ] = {}

        for label, stats in split_values.items():
            known_values = stats.pop(
                "_known_values"
            )

            stats[
                "known_likelihood_distribution"
            ] = likelihood_summary(
                known_values
            )

            finalized_class_stats[
                split
            ][
                label
            ] = stats

    report = {
        "audit_timestamp_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),

        "purpose":
            "inspect annotation metadata before defining label reliability",

        "scientific_score_defined":
            False,

        "important_interpretation_rules": {
            "validated_by":
                "cardiologist identifier, not confidence",

            "validated_by_human":
                "conservative human-validation indicator, not continuous confidence",

            "likelihood_zero":
                "unknown/unavailable likelihood, not zero diagnostic confidence",

            "second_opinion":
                "presence of second opinion; no assumed direction of reliability",
        },

        "source_sha256": {
            "ptbxl_database":
                sha256_file(
                    DATABASE_PATH
                ),

            "scp_statements":
                sha256_file(
                    SCP_PATH
                ),

            "frozen_manifest":
                sha256_file(
                    MANIFEST_PATH
                ),
        },

        "provenance_by_split":
            provenance_by_split,

        "record_level_likelihood_coverage":
            record_level,

        "classwise_likelihood_audit":
            finalized_class_stats,

        "target_reconstruction_from_source_scp_codes":
            "PASS",

        "validation_and_test_human_validation_constraint":
            "PASS",

        "status":
            "PASS",
    }

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with OUTPUT_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            report,
            handle,
            indent=2,
            sort_keys=True,
        )
        handle.write(
            "\n"
        )

    print(
        json.dumps(
            report,
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
